# Generated by Django 2.0.1 on 2018-01-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, default='', max_length=200)),
                ('lastUpdate', models.DateTimeField(blank=True, default=None)),
                ('validFor_startDateTime', models.DateTimeField(blank=True, default=None)),
                ('validFor_endDateTime', models.DateTimeField(blank=True, default=None)),
                ('lifecycleStatus', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, default=None, null=True)),
                ('validFor_startDateTime', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('validFor_endDateTime', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lifecycleStatus', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('parentId', models.CharField(default='', max_length=200)),
                ('isRoot', models.BooleanField(default=False)),
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('catalog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalogManagement.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, max_length=200)),
                ('validFor_startDateTime', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('validFor_endDateTime', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('name', models.TextField(blank=True, default='')),
                ('role', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('catalog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedParty', to='catalogManagement.Catalog')),
            ],
        ),
    ]
