# Generated by Django 2.0.1 on 2018-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relatedparty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
