# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='json',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='isRoot',
            field=models.CharField(default='false', max_length=5),
        ),
        migrations.AddField(
            model_name='category',
            name='lastUpdate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='lifecycleStatus',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='parentId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='validFor_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='validFor_start',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='version',
            field=models.CharField(default='', max_length=200),
        ),
    ]
