# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0002_auto_20171106_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lastUpdate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='lifecycleStatus',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='validFor_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='validFor_start',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
