# Generated by Django 2.0.1 on 2018-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0003_auto_20180124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedparty',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
