# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0003_auto_20171106_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validFor_start', models.DateTimeField(default=None, null=True)),
                ('validFor_end', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.RemoveField(
            model_name='category',
            name='validFor_end',
        ),
        migrations.RemoveField(
            model_name='category',
            name='validFor_start',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='category',
            name='validFor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogManagement.ValidFor'),
        ),
    ]
