# Generated by Django 2.0.1 on 2018-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0004_auto_20180201_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedparty',
            name='href',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='relatedparty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
