# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0004_auto_20171110_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='validfor',
            old_name='validFor_end',
            new_name='endDateTime',
        ),
        migrations.RenameField(
            model_name='validfor',
            old_name='validFor_start',
            new_name='startDateTime',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
