# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0005_auto_20171110_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validfor',
            name='endDateTime',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='validfor',
            name='startDateTime',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
