# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0006_auto_20171113_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentId',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
