# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0008_auto_20171115_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
    ]
