# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0009_auto_20171115_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validfor',
            name='startDateTime',
            field=models.CharField(max_length=200),
        ),
    ]
