# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0011_auto_20171115_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, default='', max_length=200)),
                ('version', models.CharField(blank=True, default='', max_length=200)),
                ('lastUpdate', models.DateTimeField(blank=True, default=None)),
                ('lifecycleStatus', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.TextField(blank=True, default='')),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('validFor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogManagement.ValidFor')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='parentId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogManagement.Category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='relatedParty',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogManagement.RelatedParty'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='validFor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogManagement.ValidFor'),
        ),
    ]
