# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogManagement', '0012_auto_20171117_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedparty',
            name='validFor',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='relatedParty',
        ),
        migrations.DeleteModel(
            name='RelatedParty',
        ),
    ]
